spring:
  profiles:
    active: dev
  #关闭缓存
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5

  #数据库连接设置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://paidaxin.ink:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
       #连接池名
      pool-name: DateHikaricp
        #最小空闲连接出
      minimum-idle: 5
        #空闲连接最大存活时间，默认600000（十分钟）
      idle-timeout: 180000
        #最大连接数，默认10
      maximum-pool-size: 10
        #从连接池返回的连接信息自动提交
      auto-commit: true
        #连接存活最大时间，0表示永久，默认1800000（30分钟）
      max-lifetime: 1800000
        #连接超时时间，默认30000（30秒）
      connection-timeout: 30000
        #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  #redis配置
  redis:
    #服务器地址
    host: paidaxin.ink
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5

  #ActiveMQ配置
  activemq:
    #格式 tcp://IP:端口
    broker-url: tcp://paidaxin.ink:61616
    #用户名
    user: admin
    #密码
    password: admin
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true

mybaris-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliase-package: com.yang.seckillsys.pojo
  configuration :
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



logging:
  level:
    com.yang.seckillsys.mapper: debug


